#!/usr/bin/env python3
"""Offline checks only for combined-fastpay-20260925 (adapted from combined-devnet-20260921).
This does not run fleet preflight or create rollout state."""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path, PurePosixPath
import sys
import tempfile

PACKET = Path(__file__).resolve().parent
REPO = PACKET.parents[1]
sys.path.insert(0, str(REPO / "python"))
from postfiat_ops import safe_rollout as rollout

def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def check(condition, reason):
    if not condition:
        raise RuntimeError(reason)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stage", type=Path, required=True)
    parser.add_argument("--require-signed", action="store_true")
    args = parser.parse_args()
    stage = args.stage.resolve()
    unsigned = json.loads((PACKET / "manifest-input.unsigned.json").read_text())
    report_path = stage / "stage-report.json"
    report = json.loads(report_path.read_text())
    release = unsigned["deployment_id"]
    rootfs = stage / "rootfs"
    config = rootfs / "etc/postfiat/releases" / release
    binary = rootfs / "opt/postfiat/releases" / release / "postfiat-node"
    check(report["schema"] == rollout.STAGE_SCHEMA, "stage schema")
    check(report["release_id"] == release and Path(report["rootfs_dir"]) == rootfs, "stage location")
    check(sha(binary) == unsigned["binary_sha256"], "qualified binary hash")
    check(sha(config / "deployment.public.json") == unsigned["trusted_publisher_file_sha256"], "publisher trust hash")
    # As in r4, the manifest's top-level unit/environment are validator-0's RPC unit and environment.
    check(sha(stage / unsigned["service_unit_file"]) == unsigned["service_unit_sha256"], "top-level unit")
    check(sha(stage / unsigned["environment_file"]) == unsigned["environment_sha256"], "top-level environment")
    inventory = rollout.parse_inventory(PACKET / "inventory.txt")
    ids = [f"validator-{i}" for i in range(6)]
    check([r["validator_id"] for r in report["validators"]] == ids, "stage validator IDs")
    topology = json.loads((config / "topology.json").read_text())
    check([r["node_id"] for r in topology["peers"]] == ids, "topology validator IDs")
    for field in ("chain_id", "genesis_hash", "protocol_version"):
        check(topology[field] == unsigned[field], f"topology {field}")
    for entry, peer in zip(inventory, topology["peers"]):
        check((entry.p2p_port, entry.rpc_port) == (peer["p2p_port"], peer["rpc_port"]), "inventory ports")
    check(rollout.rollout_order("validator-1") == ["validator-1", "validator-0", "validator-2", "validator-3", "validator-4", "validator-5"], "canary order")
    golden_count = 0
    for golden in sorted((PACKET / "rootfs").rglob("*")):
        if golden.is_file():
            path = rootfs / golden.relative_to(PACKET / "rootfs")
            check(golden.read_bytes() == path.read_bytes(), f"generated bytes differ: {path}")
            golden_count += 1
    for name, field in [
        ("topology.json", "topology_sha256"),
        ("swap.metadata.json", "swap_circuit_metadata_sha256"),
        ("private-egress.metadata.json", "private_egress_circuit_metadata_sha256"),
    ]:
        check(sha(config / name) == unsigned[field], f"{name} hash")
    circuit_count = 0
    for name in ("swap.metadata.json", "private-egress.metadata.json"):
        for circuit in json.loads((config / name).read_text())["sets"]:
            artifact = REPO / circuit["embedded_artifact_path"]
            check(sha(artifact) == circuit["embedded_artifact_sha256"], f"circuit artifact {artifact}")
            check(artifact.stat().st_size == circuit["embedded_artifact_bytes"], "circuit artifact size")
            circuit_count += 1
    signing = json.loads((stage / "validator-bindings.signing.json").read_text())
    check(signing["schema"] == "postfiat.deployment_validator_bindings.v1", "signing schema")
    check([r["validator_id"] for r in signing["validators"]] == ids, "signing validator IDs")
    results = []
    for row, expected in zip(signing["validators"], unsigned["validator_bindings"]):
        validator = row["validator_id"]
        check([s["service_id"] for s in row["services"]] == ["rpc", "transport"], "service order")
        runtime = json.loads((config / f"{validator}.bindings.json").read_text())
        check(runtime["schema"] == signing["schema"], "runtime binding schema")
        check([r["validator_id"] for r in runtime["validators"]] == [validator], "runtime binding ID")
        runtime_services = runtime["validators"][0]["services"]
        check([s["service_id"] for s in runtime_services] == ["rpc", "transport"], "runtime service order")
        entries = []
        for service, want, runtime_service in zip(row["services"], expected["services"], runtime_services):
            for field, hash_field in [("service_unit_file", "service_unit_sha256"), ("environment_file", "environment_sha256")]:
                target = PurePosixPath(runtime_service[field])
                source = rollout._require_source(rootfs, target)
                check(Path(service[field]) == source, f"binding location: {validator}")
                check(sha(source) == want[hash_field], f"binding hash: {validator}")
                entries.append(rollout.CopyEntry(source, target))
        # Validate every present destination against the production allowlist.
        for name in ["topology.json", "swap.metadata.json", "private-egress.metadata.json",
                     "deployment.public.json", f"{validator}.bindings.json"]:
            target = PurePosixPath(f"/etc/postfiat/releases/{release}/{name}")
            entries.append(rollout.CopyEntry(rollout._require_source(rootfs, target), target))
        target = PurePosixPath(f"/opt/postfiat/releases/{release}/postfiat-node")
        entries.append(rollout.CopyEntry(rollout._require_source(rootfs, target), target))
        rollout.validate_copy_entries(entries, release, validator)
        refusal = None
        if args.require_signed:
            rollout.verify_local_stage(rollout.Runner(), report_path, validator)
            result = "PASS_SIGNED_LOCAL_VERIFICATION"
        else:
            try:
                rollout.verify_local_stage(rollout.Runner(), report_path, validator)
            except rollout.SafetyError as error:
                check("required staged file is missing:" in str(error) and str(error).endswith("/deployment-manifest.json"), str(error))
                refusal = str(error)
                result = "BLOCKED_MISSING_SIGNED_MANIFEST"
            else:
                raise RuntimeError("unsigned preparation unexpectedly passed signed gate")
        results.append({"validator_id": validator, "inputs": "PASS", "allowlisted_present_files": len(entries), "manifest_gate": result, "manifest_gate_error": refusal})
    print(json.dumps({
        "checked_at": datetime.now(timezone.utc).isoformat(),
        "result": "PASS_LOCAL_INPUTS_ONLY" if not args.require_signed else "PASS_SIGNED_LOCAL_INPUTS_ONLY",
        "network_calls": 0, "rollout_state_created": False,
        "binary_sha256": sha(binary), "canonical_generated_files": golden_count,
        "circuit_artifacts_matched": circuit_count, "inventory_parse": "PASS_HISTORICAL_IDENTITIES_ONLY",
        "canary_order": rollout.rollout_order("validator-1"), "validators": results,
    }, indent=2))

if __name__ == "__main__":
    # The production verifier creates temporary local bindings; retain them under ~/.cache.
    scratch = Path.home() / ".cache/deploy-combined-fastpay-20260925/tmp"
    scratch.mkdir(parents=True, exist_ok=True)
    tempfile.tempdir = str(scratch)
    main()
