[profile.default]
src = "src"
script = "script"
test = "test"
out = "out"
cache_path = "cache"
libs = ["../../external/sp1-contracts/contracts"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4
