[package]
name = "reserve-proof-types"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[features]
default = ["a666-public-adapters-v2"]
a666-public-adapters-v2 = [
    "dep:base64",
    "dep:bs58",
    "dep:serde_json",
    "dep:sha2",
    "dep:thiserror",
]

[dependencies]
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-trie.workspace = true
base64 = { workspace = true, optional = true }
bs58 = { workspace = true, optional = true }
ed25519-dalek.workspace = true
hex.workspace = true
postfiat-crypto-provider.workspace = true
postfiat-types.workspace = true
serde.workspace = true
serde_json = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
sha3.workspace = true
thiserror = { workspace = true, optional = true }

[dev-dependencies]
k256.workspace = true
serde_json.workspace = true
