"""Tests for the genesis-registry reference builder and verifier.

The core acceptance bar is two-implementation hash agreement: the golden
vectors under ``benchmarks/genesis-registry/fixtures/`` were generated by the
Rust canonical types (``cargo test -p postfiat-types`` with
``GENESIS_REGISTRY_FIXTURES_REGEN=1``), and the Python builder must reproduce
the same canonical CBOR and domain-separated content hashes from the same
archived round artifacts while sharing no canonicalization code.
"""

from __future__ import annotations

import io
import json
import unittest
from contextlib import redirect_stdout
from pathlib import Path

from postfiat_rpc import genesis_registry

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURES = REPO_ROOT / "benchmarks/genesis-registry/fixtures"
ROUNDS = REPO_ROOT / "benchmarks/ai-governance/dunl-subscorer-shadow-20260901/rounds"
FIXTURE_ROUNDS = tuple(range(12, 20))
MUTATION_COUNT = 25
ROUND_ARCHIVE_AVAILABLE = (
    ROUNDS / "testnet-r12/inputs/model_request.json"
).is_file()


def _golden(round_number: int) -> dict:
    path = FIXTURES / f"golden/testnet-r{round_number}.json"
    return json.loads(path.read_text())


def _build(round_number: int) -> dict:
    return genesis_registry.build_registry(
        ROUNDS / f"testnet-r{round_number}",
        FIXTURES / f"receipts/testnet-r{round_number}.json",
    )


class TwoImplementationAgreementTests(unittest.TestCase):
    @unittest.skipUnless(
        ROUND_ARCHIVE_AVAILABLE,
        "frozen round archive is intentionally fetched out-of-tree",
    )
    def test_python_build_reproduces_rust_golden_hashes(self) -> None:
        """The Rust fixture generation and the Python builder must agree."""
        for round_number in FIXTURE_ROUNDS:
            with self.subTest(round=round_number):
                golden = _golden(round_number)
                built = _build(round_number)
                self.assertEqual(
                    built["proposed_registry_hash_hex"],
                    golden["proposed_registry_hash_hex"],
                )
                self.assertEqual(built["canonical_cbor_hex"], golden["canonical_cbor_hex"])
                self.assertEqual(built["registry"], golden["registry"])

    def test_decode_round_trips_golden_cbor(self) -> None:
        for round_number in FIXTURE_ROUNDS:
            with self.subTest(round=round_number):
                golden = _golden(round_number)
                decoded = genesis_registry.decode_registry(
                    bytes.fromhex(golden["canonical_cbor_hex"])
                )
                self.assertEqual(decoded, golden["registry"])

    def test_round_19_carries_the_selected_receipted_intersection(self) -> None:
        registry = _golden(19)["registry"]
        self.assertEqual(len(registry["entries"]), 18)
        self.assertEqual(registry["template_trust_graph"], {"n_s": 18, "q_s": 15, "t_s": 4})
        full_round = _golden(18)["registry"]
        self.assertEqual(len(full_round["entries"]), 20)
        self.assertEqual(full_round["template_trust_graph"], {"n_s": 20, "q_s": 16, "t_s": 4})

    def test_receipt_and_evidence_digests_are_recomputed_not_copied(self) -> None:
        """Entry digests must equal fresh Python recomputations."""
        receipts = json.loads((FIXTURES / "receipts/testnet-r12.json").read_text())
        by_key = {r["fork_master_key_hex"]: r for r in receipts["receipts"]}
        for entry in _golden(12)["registry"]["entries"]:
            receipt = by_key[entry["fork_master_key_hex"]]
            self.assertEqual(
                entry["identity_receipt_digest_hex"],
                genesis_registry.receipt_hash(receipt).hex(),
            )


class MutationRejectionTests(unittest.TestCase):
    def test_every_mutation_fixture_is_rejected_with_its_named_error(self) -> None:
        paths = sorted((FIXTURES / "mutations/testnet-r12").glob("*.json"))
        self.assertEqual(len(paths), MUTATION_COUNT)
        for path in paths:
            fixture = json.loads(path.read_text())
            with self.subTest(mutation=fixture["name"]):
                with self.assertRaises(genesis_registry.GenesisRegistryError) as ctx:
                    genesis_registry.decode_registry(bytes.fromhex(fixture["cbor_hex"]))
                self.assertEqual(ctx.exception.code, fixture["expected_error"])

    def test_verify_reports_mutations_as_failures(self) -> None:
        path = FIXTURES / "mutations/testnet-r12/version_unknown.json"
        report = genesis_registry.verify_payload(
            path, ROUNDS / "testnet-r12", FIXTURES / "receipts/testnet-r12.json"
        )
        self.assertFalse(report["ok"])
        self.assertEqual(report["error"], "unknown_version")


class TrustGraphTests(unittest.TestCase):
    def test_template_examples(self) -> None:
        cases = {12: (10, 3), 18: (15, 4), 20: (16, 4)}
        for n, (q, t) in cases.items():
            graph = genesis_registry.template_trust_graph(n)
            self.assertEqual((graph["q_s"], graph["t_s"]), (q, t))

    def test_unsafe_sizes_rejected(self) -> None:
        for n in (0, 1, 2):
            with self.assertRaises(genesis_registry.GenesisRegistryError):
                genesis_registry.template_trust_graph(n)


class CliTests(unittest.TestCase):
    def _run(self, argv: list[str]) -> tuple[int, str]:
        stream = io.StringIO()
        with redirect_stdout(stream):
            code = genesis_registry.main(argv)
        return code, stream.getvalue()

    @unittest.skipUnless(
        ROUND_ARCHIVE_AVAILABLE,
        "frozen round archive is intentionally fetched out-of-tree",
    )
    def test_build_json_matches_golden_hash(self) -> None:
        code, output = self._run(
            [
                "build",
                "--round-dir",
                str(ROUNDS / "testnet-r12"),
                "--receipts",
                str(FIXTURES / "receipts/testnet-r12.json"),
                "--json",
            ]
        )
        self.assertEqual(code, 0)
        self.assertEqual(
            json.loads(output)["proposed_registry_hash_hex"],
            _golden(12)["proposed_registry_hash_hex"],
        )

    @unittest.skipUnless(
        ROUND_ARCHIVE_AVAILABLE,
        "frozen round archive is intentionally fetched out-of-tree",
    )
    def test_verify_golden_payload_ok(self) -> None:
        code, output = self._run(
            [
                "verify",
                "--payload",
                str(FIXTURES / "golden/testnet-r12.json"),
                "--round-dir",
                str(ROUNDS / "testnet-r12"),
                "--receipts",
                str(FIXTURES / "receipts/testnet-r12.json"),
                "--json",
            ]
        )
        self.assertEqual(code, 0)
        report = json.loads(output)
        self.assertTrue(report["ok"])
        self.assertTrue(report["hash_match"] and report["bytes_match"])

    def test_verify_mutation_payload_fails(self) -> None:
        code, output = self._run(
            [
                "verify",
                "--payload",
                str(FIXTURES / "mutations/testnet-r12/entries_unsorted.json"),
                "--round-dir",
                str(ROUNDS / "testnet-r12"),
                "--receipts",
                str(FIXTURES / "receipts/testnet-r12.json"),
                "--json",
            ]
        )
        self.assertEqual(code, 1)
        self.assertEqual(json.loads(output)["error"], "unsorted_entries")

    def test_explain_summarizes_payload(self) -> None:
        code, output = self._run(
            ["explain", "--payload", str(FIXTURES / "golden/testnet-r19.json"), "--json"]
        )
        self.assertEqual(code, 0)
        report = json.loads(output)
        self.assertEqual(report["entries"], 18)
        self.assertEqual(report["cutoff"], 40)
        self.assertEqual(
            report["proposed_registry_hash_hex"], _golden(19)["proposed_registry_hash_hex"]
        )


if __name__ == "__main__":
    unittest.main()
